# Generated by Django 3.1 on 2020-08-28 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Source',
            new_name='Subject',
        ),
    ]
